export const COUNTRIES = [
    { code: "91", name: "India", flag: "🇮🇳" },
    { code: "977", name: "Nepal", flag: "🇳🇵" },
    { code: "92", name: "Pakistan", flag: "🇵🇰" },
    { code: "880", name: "Bangladesh", flag: "🇧🇩" },
    { code: "94", name: "Sri Lanka", flag: "🇱🇰" },
    { code: "975", name: "Bhutan", flag: "🇧🇹" },
    { code: "960", name: "Maldives", flag: "🇲🇻" },
    { divider: true },
    { code: "971", name: "UAE", flag: "🇦🇪" },
    { code: "966", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "974", name: "Qatar", flag: "🇶🇦" },
    { code: "965", name: "Kuwait", flag: "🇰🇼" },
    { code: "968", name: "Oman", flag: "🇴🇲" },
    { code: "973", name: "Bahrain", flag: "🇧 Bahrain" },
    { code: "972", name: "Israel", flag: "🇮🇱" },
    { divider: true },
    { code: "1", name: "USA / Canada", flag: "🇺🇸" },
    { code: "44", name: "UK", flag: "🇬🇧" },
    { code: "61", name: "Australia", flag: "🇦🇺" },
    { code: "64", name: "New Zealand", flag: "🇳🇿" },
    { divider: true },
    { code: "86", name: "China", flag: "🇨🇳" },
    { code: "81", name: "Japan", flag: "🇯🇵" },
    { code: "82", name: "South Korea", flag: "🇰🇷" },
    { code: "65", name: "Singapore", flag: "🇸🇬" },
    { code: "60", name: "Malaysia", flag: "🇲🇾" },
    { code: "62", name: "Indonesia", flag: "🇮🇩" },
    { code: "63", name: "Philippines", flag: "🇵🇭" },
    { code: "66", name: "Thailand", flag: "🇹🇭" },
    { code: "84", name: "Vietnam", flag: "🇻🇳" },
    { divider: true },
    { code: "49", name: "Germany", flag: "🇩🇪" },
    { code: "33", name: "France", flag: "🇫🇷" },
    { code: "39", name: "Italy", flag: "🇮🇹" },
    { code: "34", name: "Spain", flag: "🇪🇸" },
    { code: "31", name: "Netherlands", flag: "🇳🇱" },
    { code: "41", name: "Switzerland", flag: "🇨🇭" },
    { code: "46", name: "Sweden", flag: "🇸🇪" },
    { code: "47", name: "Norway", flag: "🇳🇴" },
    { code: "45", name: "Denmark", flag: "🇩🇰" },
    { code: "32", name: "Belgium", flag: "🇧🇪" },
    { code: "48", name: "Poland", flag: "🇵🇱" },
    { code: "7", name: "Russia", flag: "🇷🇺" },
    { divider: true },
    { code: "27", name: "South Africa", flag: "🇿🇦" },
    { code: "234", name: "Nigeria", flag: "🇳🇬" },
    { code: "254", name: "Kenya", flag: "🇰🇪" },
    { code: "20", name: "Egypt", flag: "🇪🇬" },
    { divider: true },
    { code: "55", name: "Brazil", flag: "🇧🇷" },
    { code: "52", name: "Mexico", flag: "🇲🇽" },
    { code: "54", name: "Argentina", flag: "🇦🇷" },
    { code: "57", name: "Colombia", flag: "🇨🇴" },
];
